# Generated by Django 6.1 on 2026-08-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='farmer_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
