# Generated by Django 6.1.1 on 2026-09-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_farmer_id'),
        ('procurement', '0002_procurementcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='procurement.procurementcenter'),
        ),
    ]
