# Generated by Django 6.1 on 2026-08-29 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('KG', 'Kilograms'), ('QUINTAL', 'Quintals'), ('TONNE', 'Tonnes')], max_length=20)),
                ('harvest_date', models.DateField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REQUESTED', 'Procurement Requested'), ('PROCURED', 'Procured')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
