# Generated by Django 6.1.1 on 2026-09-04 17:19

from django.db import migrations, models


def seed_msp_crops(apps, schema_editor):
    MSPCrop = apps.get_model("produce", "MSPCrop")
    crops = [
        # Kharif Crops
        ("Paddy (Rice)", "KHARIF"),
        ("Wheat", "RABI"),
        ("Jowar (Sorghum)", "KHARIF"),
        ("Bajra (Pearl Millet)", "KHARIF"),
        ("Maize", "KHARIF"),
        ("Ragi (Finger Millet)", "KHARIF"),
        ("Arhar / Tur (Pigeon Pea)", "KHARIF"),
        ("Moong (Green Gram)", "KHARIF"),
        ("Urad (Black Gram)", "KHARIF"),
        ("Gram (Chickpea)", "RABI"),
        ("Masur (Lentil)", "RABI"),
        ("Groundnut", "KHARIF"),
        ("Sunflower Seed", "KHARIF"),
        ("Soyabean", "KHARIF"),
        ("Sesamum (Til)", "KHARIF"),
        ("Nigerseed", "KHARIF"),
        ("Rapeseed & Mustard", "RABI"),
        ("Safflower", "RABI"),
        ("Cotton", "COMMERCIAL"),
        ("Copra (De-husked Coconut)", "COMMERCIAL"),
        ("Raw Jute", "COMMERCIAL"),
        ("Sugarcane", "COMMERCIAL"),
        ("Barley", "RABI"),
    ]
    for name, category in crops:
        MSPCrop.objects.get_or_create(name=name, defaults={"category": category})


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSPCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('KHARIF', 'Kharif Crop'), ('RABI', 'Rabi Crop'), ('COMMERCIAL', 'Commercial / Other Crop')], default='KHARIF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MSP Crop',
                'verbose_name_plural': 'MSP Crops',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_msp_crops, reverse_code=migrations.RunPython.noop),
    ]

