# Generated by Django 6.1.1 on 2026-09-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0002_mspcrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Address used to calculate nearest procurement center', verbose_name='Farm / Pickup Address'),
        ),
    ]
