# Generated by Django 6.1.1 on 2026-09-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0003_produce_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='district',
            field=models.CharField(default='Lucknow', help_text='District used to locate nearest procurement centers in UP', max_length=100, verbose_name='District (Uttar Pradesh)'),
        ),
    ]
