# Generated by Django 6.1.1 on 2026-09-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0004_procurementrecord_vehicle_number'),
        ('produce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time_slot', models.CharField(choices=[('09:00 AM - 10:00 AM', '09:00 AM – 10:00 AM'), ('10:00 AM - 11:00 AM', '10:00 AM – 11:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM – 12:00 PM'), ('12:00 PM - 01:00 PM', '12:00 PM – 01:00 PM'), ('02:00 PM - 03:00 PM', '02:00 PM – 03:00 PM'), ('03:00 PM - 04:00 PM', '03:00 PM – 04:00 PM')], default='10:00 AM - 11:00 AM', max_length=50)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], default='CONFIRMED', max_length=20)),
                ('token_number', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('procurement_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='procurement.procurementcenter')),
                ('procurement_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='procurement.procurementrecord')),
                ('produce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='produce.produce')),
            ],
            options={
                'ordering': ['-appointment_date', 'appointment_time_slot'],
            },
        ),
    ]
