# Generated by Django 6.1.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('procurement', '0004_procurementrecord_vehicle_number'),
        ('produce', '0004_produce_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='procurement_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='procurement.procurementrecord'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='produce.produce'),
        ),
    ]
