# Generated by Django 6.1.1 on 2026-09-04 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('registered_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(default='Quintals', max_length=20)),
                ('center_name', models.CharField(default='Lucknow Procurement Hub', max_length=150)),
                ('counter_number', models.CharField(default='Counter 2', max_length=20)),
                ('token_number', models.CharField(default='A-104', max_length=50)),
                ('appointment_date', models.CharField(default='12 September 2026, 10:30 AM', max_length=100)),
                ('current_stage', models.CharField(choices=[('REGISTERED', 'Produce Registered'), ('APPOINTMENT', 'Appointment Confirmed'), ('ARRIVED', 'Farmer Arrived'), ('VERIFICATION', 'Verification'), ('QUALITY', 'Quality Check'), ('WEIGHING', 'Weighing'), ('PROCURED', 'Procurement Confirmed'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('PAYMENT_COMPLETED', 'Payment Completed')], default='WEIGHING', max_length=30)),
                ('is_identity_verified', models.BooleanField(default=True)),
                ('is_produce_verified', models.BooleanField(default=True)),
                ('is_request_verified', models.BooleanField(default=True)),
                ('verified_by', models.CharField(default='Officer R. Sharma', max_length=100)),
                ('quality_grade', models.CharField(default='Grade A', max_length=10)),
                ('moisture_content', models.CharField(default='11.5%', max_length=20)),
                ('quality_status', models.CharField(default='Good', max_length=50)),
                ('officer_remarks', models.TextField(default='Produce meets procurement standards')),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=2275.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=110692.5, max_digits=12)),
                ('payment_status', models.CharField(default='Processing', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
