# Generated by Django 6.1.1 on 2026-09-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=100)),
                ('tehsil_block', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(default='+91 94150 12345', max_length=20)),
                ('operating_hours', models.CharField(default='08:00 AM - 05:00 PM', max_length=50)),
                ('crops_handled', models.CharField(default='Wheat, Paddy, Mustard, Gram', max_length=200)),
                ('queue_status', models.CharField(choices=[('LOW', 'Low Queue'), ('MEDIUM', 'Medium Queue'), ('HIGH', 'High Queue')], default='LOW', max_length=10)),
                ('distance_km', models.DecimalField(decimal_places=1, default=4.5, max_digits=5)),
                ('capacity_quintals', models.IntegerField(default=5000)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Procurement Center',
                'verbose_name_plural': 'Procurement Centers',
                'ordering': ['district', 'name'],
            },
        ),
    ]
