# Generated by Django 6.1.1 on 2026-09-04 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_procurementcenter'),
        ('produce', '0004_produce_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurementrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='procurementcenter',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='procurementrecord',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_records', to='procurement.procurementcenter'),
        ),
        migrations.AddField(
            model_name='procurementrecord',
            name='gate_entry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementrecord',
            name='produce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_records', to='produce.produce'),
        ),
        migrations.AddField(
            model_name='procurementrecord',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='appointment_date',
            field=models.CharField(default='Today, 10:00 AM', max_length=100),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='counter_number',
            field=models.CharField(default='Counter 1', max_length=20),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='current_stage',
            field=models.CharField(choices=[('REGISTRATION', 'Produce Registered'), ('APPOINTMENT', 'Appointment Confirmed'), ('GATE_ENTRY', 'Gate Entry'), ('QUALITY_CHECK', 'Quality Check'), ('WEIGHING', 'Weighing'), ('ACCEPTANCE', 'Acceptance'), ('BILL_GENERATED', 'Bill Generated'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_RECEIVED', 'Payment Received'), ('COMPLETED', 'Procurement Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='REGISTRATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='is_produce_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='is_request_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='officer_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='quality_grade',
            field=models.CharField(default='Grade A', max_length=20),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='quality_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='token_number',
            field=models.CharField(default='A-101', max_length=50),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ProcurementAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='procurement.procurementcenter')),
                ('procurement_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='procurement.procurementrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('quantity_quintals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_bills', to=settings.AUTH_USER_MODEL)),
                ('procurement_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='procurement.procurementrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('RECEIVED', 'Received'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=100)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payments', to=settings.AUTH_USER_MODEL)),
                ('procurement_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='procurement.procurementrecord')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='procurement.procurementbill')),
            ],
        ),
        migrations.CreateModel(
            name='QualityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_grade', models.CharField(choices=[('GRADE_A', 'Grade A (FAQ)'), ('GRADE_B', 'Grade B'), ('GRADE_C', 'Grade C')], default='GRADE_A', max_length=20)),
                ('moisture_percentage', models.DecimalField(decimal_places=2, default=11.5, max_digits=5)),
                ('foreign_matter_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('damaged_percentage', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('result', models.CharField(choices=[('PASSED', 'Passed'), ('REJECTED', 'Rejected')], default='PASSED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessments', to=settings.AUTH_USER_MODEL)),
                ('procurement_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessment', to='procurement.procurementrecord')),
            ],
        ),
        migrations.CreateModel(
            name='WeighingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tare_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='Quintals', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('weighed_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighing_records', to=settings.AUTH_USER_MODEL)),
                ('procurement_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weighing_record', to='procurement.procurementrecord')),
            ],
        ),
    ]
