# Generated by Django 6.1.1 on 2026-09-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_procurementrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrecord',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
