# Generated by Django 6.1.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_procurement_record_and_more'),
        ('procurement', '0004_procurementrecord_vehicle_number'),
        ('tokens', '0002_token_issued_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='token',
            name='procurement_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='procurement.procurementrecord'),
        ),
        migrations.AlterField(
            model_name='token',
            name='sequence_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_number',
            field=models.CharField(max_length=50),
        ),
    ]
